package org.springframework.samples.petclinic.a;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

import java.math.BigDecimal;

/**
 * Purpose: Represents a product entity in the application.
 * How to use: Used by the persistence layer to store and retrieve product data.
 * This entity maps to the 'products' table in the database.
 */
@Entity
@Table(name = "products")
public class Product {

	/**
	 * Purpose: The unique identifier for the product.
	 * How to use: Automatically generated by the database upon creation.
	 */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;

	/**
	 * Purpose: The name of the product.
	 * How to use: A required field for identifying the product.
	 */
	@Column(name = "name")
	private String name;

	/**
	 * Purpose: A detailed description of the product.
	 * How to use: Provides additional information about the product.
	 */
	@Column(name = "description")
	private String description;

	/**
	 * Purpose: The price of the product.
	 * How to use: Stored as a BigDecimal to ensure precision in monetary values.
	 */
	@Column(name = "price")
	private BigDecimal price;

	/**
	 * Purpose: Indicates whether the product is currently available.
	 * How to use: A boolean flag to manage product visibility and purchase options.
	 */
	@Column(name = "available")
	private Boolean available;

	/**
	 * Purpose: Default constructor for JPA.
	 * How to use: Required by JPA, should not be called directly for object creation.
	 */
	public Product() {
	}

	/**
	 * Purpose: Constructs a new Product with the specified details.
	 * How to use: Used to create new Product instances.
	 * @param id The unique identifier of the product.
	 * @param name The name of the product.
	 * @param description A detailed description of the product.
	 * @param price The price of the product.
	 * @param available Indicates if the product is available.
	 */
	public Product(Long id, String name, String description, BigDecimal price, Boolean available) {
		this.id = id;
		this.name = name;
		this.description = description;
		this.price = price;
		this.available = available;
	}

	/**
	 * Purpose: Retrieves the unique identifier of the product.
	 * How to use: Call to get the product's ID.
	 * @return The product's ID.
	 */
	public Long getId() {
		return id;
	}

	/**
	 * Purpose: Sets the unique identifier of the product.
	 * How to use: Primarily used by JPA when loading entities or for testing purposes.
	 * @param id The new product ID.
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * Purpose: Retrieves the name of the product.
	 * How to use: Call to get the product's name.
	 * @return The product's name.
	 */
	public String getName() {
		return name;
	}

	/**
	 * Purpose: Sets the name of the product.
	 * How to use: Call to update the product's name.
	 * @param name The new product name.
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * Purpose: Retrieves the description of the product.
	 * How to use: Call to get the product's description.
	 * @return The product's description.
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * Purpose: Sets the description of the product.
	 * How to use: Call to update the product's description.
	 * @param description The new product description.
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * Purpose: Retrieves the price of the product.
	 * How to use: Call to get the product's price.
	 * @return The product's price.
	 */
	public BigDecimal getPrice() {
		return price;
	}

	/**
	 * Purpose: Sets the price of the product.
	 * How to use: Call to update the product's price.
	 * @param price The new product price.
	 */
	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	/**
	 * Purpose: Retrieves the availability status of the product.
	 * How to use: Call to check if the product is available.
	 * @return True if the product is available, false otherwise.
	 */	
	public Boolean getAvailable() {
		return available;
	}

	/**
	 * Purpose: Sets the availability status of the product.
	 * How to use: Call to update the product's availability.
	 * @param available The new availability status.
	 */
	public void setAvailable(Boolean available) {
		this.available = available;
	}

}