package org.springframework.samples.petclinic.a;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * Simple JavaBean domain object representing a product.
 *
 * This class represents a product that can be managed in the pet clinic system.
 * It contains basic information about the product such as its name, description, and price.
 */
@Entity
@Table(name = "products")
public class Product {

    /**
     * The unique identifier for the product.
     * This field is the primary key and is automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    /**
     * The name of the product.
     * This field is used to identify the product by its name.
     */
    @Column(name = "name")
    private String name;

    /**
     * A detailed description of the product.
     * This field provides additional information about the product.
     */
    @Column(name = "description")
    private String description;

    /**
     * The price of the product.
     * This field stores the cost of the product.
     */
    @Column(name = "price")
    private double price;

    /**
     * Default constructor for a Product.
     *
     * Purpose: Required by JPA for entity instantiation.
     * How to use: Should not be called directly for creating new instances with data.
     */
    public Product() {
    }

    /**
     * Constructs a new Product with the specified details.
     *
     * Purpose: To create a new Product instance with initial data.
     * How to use: Call this constructor when you have all product details ready for creation.
     * @param name The name of the product.
     * @param description A detailed description of the product.
     * @param price The price of the product.
     */
    public Product(String name, String description, double price) {
        this.name = name;
        this.description = description;
        this.price = price;
    }

    /**
     * Returns the unique identifier of the product.
     *
     * Purpose: To retrieve the primary key of the product.
     * How to use: Call this method to get the product's ID after it has been persisted.
     * @return The product's ID.
     */
    public Integer getId() {
        return id;
    }

    /**
     * Sets the unique identifier of the product.
     *
     * Purpose: To set the primary key of the product. This is usually handled by JPA.
     * How to use: Typically not called directly in application code, managed by the persistence provider.
     * @param id The new ID for the product.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Returns the name of the product.
     *
     * Purpose: To retrieve the name of the product.
     * How to use: Call this method to display or process the product's name.
     * @return The product's name.
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the name of the product.
     *
     * Purpose: To update the name of the product.
     * How to use: Call this method to change the product's name, typically before saving.
     * @param name The new name for the product.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Returns the description of the product.
     *
     * Purpose: To retrieve the detailed description of the product.
     * How to use: Call this method to get more information about the product.
     * @return The product's description.
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the description of the product.
     *
     * Purpose: To update the description of the product.
     * How to use: Call this method to change the product's description.
     * @param description The new description for the product.
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Returns the price of the product.
     *
     * Purpose: To retrieve the price of the product.
     * How to use: Call this method to get the current price of the product.
     * @return The product's price.
     */
    public double getPrice() {
        return price;
    }

    /**
     * Sets the price of the product.
     *
     * Purpose: To update the price of the product.
     * How to use: Call this method to change the product's price.
     * @param price The new price for the product.
     */
    public void setPrice(double price) {
        this.price = price;
    }
}
